### ISSUE TITLE
(Idea) Standardise and improve

### ISSUE THREAD

**Issue by Pyromanc3r** [VintageModsReforged/AdvancedCropnalyzer-1.5.2#2]
If we install this mod, then obviously this improved item will be used, not the regular version. I was wondering if we should replace the basic Cropnalyzer with it? (by the way, currently MFR conflicts with this ID).
I've noticed that some mods like Minefactory reloaded or Railcraft replace some items with their versions while keeping the original properties. 
![items](https://github.com/user-attachments/assets/f07cef73-fcf5-43ff-9ec7-e9fa83750d73)

Maybe should do it in a similar way?
Otherwise the search is done outside of the IC2 mod, which makes it a little inconvenient (little off-top: in general, searching for mods in NEI on the current version is very inconvenient - @mod.ModName. You can't move between letters in the search field, you can only delete one letter at a time or the whole line and re-enter the text).

Also is it possible to expand the inventory like in version 1.12.2, although it is not necessary?
![1 12crop](https://github.com/user-attachments/assets/07075a43-e311-4efc-8484-5b57c7f56477)

**Comment by CrossVas** [comment]
Jeez, I get sick of this system with IDs already. Luckily you can change it yourself, otherwise it would require me to implement an auto ID assignment feature.

About anything else, I'll check what MFR and RailCraft does with duplicates. Or, I could just add the crop analyzer to the IC2 items nei group.

For the rest, I'll reply later.

**Comment by Pyromanc3r** [comment]
>you can change it yourself

Yeah, already changed it. GregTech has a handy feature to detect ID conflicts. You can open the `ForgeModLoader-client-0.log` file and search for `CONFLICT @` and it will tell you which items had conflicts and were replaced by other mods.

**Comment by CrossVas** [comment]
So, to give a full reply on your requests:
1. I don't like the idea of replacing the regular Cropnalyzer. Instead, we use it as ingredient for the advanced one. Plus, there might be mods that depends on it, I don't want to risk. The ID conflict can be easily fixed via config.
2. Added NEI support with Advanced Cropnalyzer being inside `IC2 - Addons - AdvancedCropnalyzer` category;
![image](https://github.com/user-attachments/assets/97d8ad76-90b8-48f2-b7c7-ac320155bffa)
I'll follow this format for my other addons in the future.
3. Added extended inventory for Advanced Cropnalyzer. This one might cause problems, it's untested. 
![image](https://github.com/user-attachments/assets/b81141aa-43fd-43f7-afad-d63c960723ec)

**Comment by CrossVas** [comment]
https://github.com/VintageModsReforged/AdvancedCropnalyzer-1.5.2/releases/tag/1.0.2
